---
# tasks file for mysql
- name: installer mysql
  apt:
    name: 
      - mysql-server
      - mysql-client
      - python3-mysqldb
    state: present

- name: configurer mysql
  ini_file:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    section: mysqld
    option: bind-address
    value: 0.0.0.0
    state: present

- name: demarrer mysql
  shell: service mysql restart

- name: creer une base de donnees
  mysql_db:
    name: "{{ nom_bdd }}"

- name: supprimer la base de donnees test
  mysql_db:
    name: test
    state: absent

- name: creer un utilisateur
  mysql_user:
    name: "{{ nom_bdd }}"
    password: "{{ nom_bdd }}"
    priv: "{{nom_bdd}}.*:ALL"
    host: "%"
    state: present
